name: 'Setup Runtime Environment'
description: 'Setup runtime environment for various languages/frameworks'

inputs:
  language:
    description: 'Language/framework to setup'
    required: true
  version:
    description: 'Version to use'
    required: false
    default: ''

runs:
  using: composite
  steps:
    - name: Setup Node.js
      if: inputs.language == 'nodejs'
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.version || '20' }}
        cache: 'npm'

    - name: Setup Java
      if: inputs.language == 'java'
      uses: actions/setup-java@v4
      with:
        java-version: ${{ inputs.version || '21' }}
        distribution: 'temurin'
        cache: 'maven'

    - name: Setup Python
      if: inputs.language == 'python'
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.version || '3.11' }}
        cache: 'pip'

    - name: Setup Go
      if: inputs.language == 'go'
      uses: actions/setup-go@v4
      with:
        go-version: ${{ inputs.version || '1.21' }}

    - name: Setup .NET
      if: inputs.language == 'dotnet'
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ inputs.version || '8.0.x' }}
