name: 'Docker Build and Push'
description: 'Build and optionally push Docker images with Buildx'
inputs:
  dockerfile:
    description: 'Path to Dockerfile'
    required: false
    default: 'Dockerfile'
  context:
    description: 'Build context path'
    required: false
    default: '.'
  image-name:
    description: 'Docker image name'
    required: true
  tags:
    description: 'Comma-separated list of tags'
    required: false
    default: 'latest'
  push:
    description: 'Push image to registry'
    required: false
    default: 'true'
  platforms:
    description: 'Platforms to build for'
    required: false
    default: 'linux/amd64'
  docker-username:
    description: 'Docker registry username'
    required: false
  docker-password:
    description: 'Docker registry password'
    required: false
outputs:
  image-digest:
    description: 'The digest of the built image'
    value: ${{ steps.build.outputs.digest }}
runs:
  using: 'composite'
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Log in to Docker Hub
      if: ${{ inputs.push == 'true' && inputs.docker-username != '' }}
      uses: docker/login-action@v3
      with:
        username: ${{ inputs.docker-username }}
        password: ${{ inputs.docker-password }}
    - name: Build and push
      id: build
      uses: docker/build-push-action@v5
      with:
        context: ${{ inputs.context }}
        file: ${{ inputs.dockerfile }}
        platforms: ${{ inputs.platforms }}
        push: ${{ inputs.push }}
        tags: ${{ inputs.image-name }}:${{ inputs.tags }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
