name: Golden Pipeline - Node.js

on:
  workflow_call:
    inputs:
      node-version:
        description: 'Node.js version'
        required: false
        default: '20'
        type: string
      install-command:
        description: 'Install command'
        required: false
        default: 'npm ci'
        type: string
      build-command:
        description: 'Build command'
        required: false
        default: 'npm run build'
        type: string
      test-command:
        description: 'Test command'
        required: false
        default: 'npm test'
        type: string
      lint-command:
        description: 'Lint command'
        required: false
        default: 'npm run lint'
        type: string
      working-directory:
        description: 'Working directory'
        required: false
        default: '.'
        type: string
    secrets:
      NPM_TOKEN:
        required: false
      SONAR_TOKEN:
        required: false

jobs:
  # Stage 1: Code Quality & Security Scanning
  code-quality:
    name: Code Quality & Security
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}
          cache: 'npm'
          cache-dependency-path: ${{ inputs.working-directory }}/package-lock.json

      - name: Install dependencies
        working-directory: ${{ inputs.working-directory }}
        run: ${{ inputs.install-command }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      # Linting
      - name: Run ESLint
        working-directory: ${{ inputs.working-directory }}
        run: |
          if npm run | grep -q "lint"; then
            ${{ inputs.lint-command }} || true
          else
            echo "No lint script found, skipping..."
          fi
        continue-on-error: true

      # Code formatting check
      - name: Check code formatting
        working-directory: ${{ inputs.working-directory }}
        run: |
          if npm run | grep -q "format:check"; then
            npm run format:check || true
          else
            echo "No format:check script found, skipping..."
          fi
        continue-on-error: true

      # Security: SAST with CodeQL
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v4
        with:
          languages: javascript

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v4
        continue-on-error: true

      # Security: Dependency vulnerability scanning
      - name: Run npm audit
        working-directory: ${{ inputs.working-directory }}
        run: |
          npm audit --audit-level=moderate --production || true
        continue-on-error: true

      # Security: OWASP Dependency Check
      - name: OWASP Dependency Check
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: '${{ github.repository }}'
          path: '${{ inputs.working-directory }}'
          format: 'ALL'
        continue-on-error: true

      # Security: Secrets scanning
      - name: Scan for secrets
        uses: trufflesecurity/trufflehog@main
        with:
          path: ${{ inputs.working-directory }}
          base: ${{ github.event.repository.default_branch }}
          head: HEAD
        continue-on-error: true

      # SonarQube (if token provided)
      - name: SonarQube Scan
        if: ${{ secrets.SONAR_TOKEN != '' }}
        working-directory: ${{ inputs.working-directory }}
        run: |
          if command -v sonar-scanner &> /dev/null || npm list -g sonarqube-scanner &> /dev/null; then
            sonar-scanner -Dsonar.login=${{ secrets.SONAR_TOKEN }} || true
          else
            echo "SonarQube scanner not available, skipping..."
          fi
        continue-on-error: true
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  # Stage 2: Build & Test
  build-and-test:
    name: Build & Test
    runs-on: ubuntu-latest
    needs: code-quality
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}
          cache: 'npm'
          cache-dependency-path: ${{ inputs.working-directory }}/package-lock.json

      - name: Install dependencies
        working-directory: ${{ inputs.working-directory }}
        run: ${{ inputs.install-command }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Run tests
        working-directory: ${{ inputs.working-directory }}
        run: ${{ inputs.test-command }}

      - name: Build application
        working-directory: ${{ inputs.working-directory }}
        run: ${{ inputs.build-command }}

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: ${{ inputs.working-directory }}/dist
          if-no-files-found: ignore

      # Code coverage
      - name: Generate coverage report
        working-directory: ${{ inputs.working-directory }}
        run: |
          if npm run | grep -q "test:coverage"; then
            npm run test:coverage || true
          else
            echo "No coverage script found, skipping..."
          fi
        continue-on-error: true

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          directory: ${{ inputs.working-directory }}
          files: ./coverage/coverage-final.json,./coverage/lcov.info
          flags: unittests
          name: codecov-umbrella
        continue-on-error: true

  # Stage 3: Container Security (if Dockerfile exists)
  container-security:
    name: Container Security
    runs-on: ubuntu-latest
    needs: build-and-test
    if: hashFiles('**/Dockerfile') != ''
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Trivy vulnerability scanner
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'

      - name: Upload Trivy results to GitHub Security
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: 'trivy-results.sarif'
        continue-on-error: true

      # Docker Scout (if available)
      - name: Docker Scout
        uses: docker/scout-action@v1
        with:
          command: cves
          image: ${{ github.repository }}
        continue-on-error: true
        if: hashFiles('**/Dockerfile') != ''

  # Stage 4: Security Summary
  security-summary:
    name: Security Summary
    runs-on: ubuntu-latest
    needs: [code-quality, build-and-test, container-security]
    if: always()
    steps:
      - name: Security scan summary
        run: |
          echo "## 🔒 Security Scan Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "✅ Code quality checks completed" >> $GITHUB_STEP_SUMMARY
          echo "✅ Dependency scanning completed" >> $GITHUB_STEP_SUMMARY
          echo "✅ Secrets scanning completed" >> $GITHUB_STEP_SUMMARY
          if hashFiles('**/Dockerfile') != ''; then
            echo "✅ Container security scanning completed" >> $GITHUB_STEP_SUMMARY
          fi
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "View detailed results in the Security tab."
