name: Security Scan

on:
  workflow_call:
    permissions:
      contents: read
      security-events: write
    inputs:
      scan-type:
        description: 'Type of security scan'
        required: false
        default: 'all'
        type: choice
        options:
          - all
          - secrets
          - dependencies
          - containers
          - infrastructure
    secrets:
      SONAR_TOKEN:
        required: false

jobs:
  secrets-scan:
    name: Secrets Scanning
    runs-on: ubuntu-latest
    if: ${{ inputs.scan-type == 'all' || inputs.scan-type == 'secrets' }}
    continue-on-error: true
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run TruffleHog
        uses: trufflesecurity/trufflehog@main
        continue-on-error: true
        with:
          path: .
          base: ${{ github.event.repository.default_branch }}
          head: HEAD

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  dependency-scan:
    name: Dependency Scanning
    runs-on: ubuntu-latest
    if: ${{ inputs.scan-type == 'all' || inputs.scan-type == 'dependencies' }}
    continue-on-error: true
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: OWASP Dependency Check
        uses: dependency-check/Dependency-Check_Action@main
        continue-on-error: true
        with:
          project: '${{ github.repository }}'
          path: '.'
          format: 'ALL'

      - name: Snyk Security Scan
        uses: snyk/actions/node@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --severity-threshold=high

  container-scan:
    name: Container Scanning
    runs-on: ubuntu-latest
    if: ${{ inputs.scan-type == 'all' || inputs.scan-type == 'containers' }}
    continue-on-error: true
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        if: hashFiles('**/Dockerfile') != ''
        run: |
          docker build -t test-image:latest .

      - name: Run Trivy vulnerability scanner
        if: hashFiles('**/Dockerfile') != ''
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'test-image:latest'
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'

      - name: Upload Trivy results
        if: hashFiles('**/Dockerfile') != ''
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: 'trivy-results.sarif'

  infrastructure-scan:
    name: Infrastructure Scanning
    runs-on: ubuntu-latest
    if: ${{ inputs.scan-type == 'all' || inputs.scan-type == 'infrastructure' }}
    continue-on-error: true
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Checkov
        if: hashFiles('**/*.tf') != ''
        uses: bridgecrewio/checkov-action@master
        with:
          directory: .
          framework: terraform
          soft_fail: true

      - name: Run Terrascan
        if: hashFiles('**/*.tf') != ''
        uses: accurics/terrascan-action@v1
        with:
          iac_type: 'terraform'
          iac_dir: '.'
          non_recursive: true
          sarif_upload: true
        continue-on-error: true

      - name: Run TFLint
        if: hashFiles('**/*.tf') != ''
        uses: terraform-linters/setup-tflint@v4
        with:
          tflint_version: latest

      - name: TFLint Check
        if: hashFiles('**/*.tf') != ''
        run: |
          tflint --init
          tflint --format=default
        continue-on-error: true
